py_lines = {
    'line 1':"Beautiful is better than ugly.",
    'line 2':"Explicit is better than implicit.",
    'line 3':"Simple is better than complex.",
    'line 4':"Complex is better than complicated.",
    'line 5':"Flat is better than nested.",
    'line 6':"Sparse is better than dense.",
    'line 7':"Readability counts.",
    'line 8':"Special cases aren't special enough to break the rules.",
    'line 9':"Although practicality beats purity.",
    'line 10':"Errors should never pass silently.",
    'line 11':"Unless explicitly silenced.",
    'line 12':"In the face of ambiguity, refuse the temptation to guess.",
    'line 13':"There should be one-- and preferably only one --obvious way to do it.",
    'line 14':"Although that way may not be obvious at first unless you're Dutch.",
    'line 15':"Now is better than never.",
    'line 16':"Although never is often better than *right* now.",
    'line 17':"If the implementation is hard to explain, it's a bad idea.",
    'line 18':"If the implementation is easy to explain, it may be a good idea.",
    'line 19':"Namespaces are one honking great idea -- let's do more of those!",
}
